// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFQOC1cieMONPwUPbfiF-sG_NXFKf73fg',
    appId: '1:198726889153:web:e673118e53a558e13aae40',
    messagingSenderId: '198726889153',
    projectId: 'medix-cfe45',
    authDomain: 'medix-cfe45.firebaseapp.com',
    storageBucket: 'medix-cfe45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnh5nczbagMqkIr4xRlHRRNH1J2Ix9Zn0',
    appId: '1:198726889153:android:fdcf9a46726002703aae40',
    messagingSenderId: '198726889153',
    projectId: 'medix-cfe45',
    storageBucket: 'medix-cfe45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcbQyyP9bglA43LWCIvEYpkJu54MoHB14',
    appId: '1:198726889153:ios:15a5ae560faec18c3aae40',
    messagingSenderId: '198726889153',
    projectId: 'medix-cfe45',
    storageBucket: 'medix-cfe45.firebasestorage.app',
    iosBundleId: 'com.example.medix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcbQyyP9bglA43LWCIvEYpkJu54MoHB14',
    appId: '1:198726889153:ios:15a5ae560faec18c3aae40',
    messagingSenderId: '198726889153',
    projectId: 'medix-cfe45',
    storageBucket: 'medix-cfe45.firebasestorage.app',
    iosBundleId: 'com.example.medix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFQOC1cieMONPwUPbfiF-sG_NXFKf73fg',
    appId: '1:198726889153:web:e22269f05bb85d073aae40',
    messagingSenderId: '198726889153',
    projectId: 'medix-cfe45',
    authDomain: 'medix-cfe45.firebaseapp.com',
    storageBucket: 'medix-cfe45.firebasestorage.app',
  );
}
